### ISSUE TITLE
`createProfile` endpoint returns gas estimation

### ISSUE THREAD

**Issue by bigint** [aave/lens-api-examples#21]
```json
{
    "errors": [
        {
            "message": "cannot estimate gas; transaction may fail or may require manual gas limit (error={\"reason\":\"cannot estimate gas; transaction may fail or may require manual gas limit\",\"code\":\"UNPREDICTABLE_GAS_LIMIT\",\"error\":{\"code\":3,\"data\":\"0x902815b9\"},\"method\":\"estimateGas\",\"transaction\":{\"from\":\"0x6C1e1bC39b13f9E0Af9424D76De899203F47755F\",\"to\":\"0xF6BF84E5df229029C9D36dC7ABaCDBE9c0bd7b4F\",\"data\":\"0xffea138e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bba7556f668a78dba5e7989b0d7ca4db6315546e00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000968656c6c6f6c656e730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a68747470733a2f2f697066732e696e667572612e696f2f697066732f516d61386d586f656f727650716f6444617a6637787141526f464433393473316e6a6b7a653771315834434b38550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d574b4a4b566a37616158796e375679717465566f4771727764414b485538684747313974695951676558416f0000000000000000000000\",\"accessList\":null}}, tx={\"data\":\"0xffea138e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bba7556f668a78dba5e7989b0d7ca4db6315546e00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000968656c6c6f6c656e730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a68747470733a2f2f697066732e696e667572612e696f2f697066732f516d61386d586f656f727650716f6444617a6637787141526f464433393473316e6a6b7a653771315834434b38550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d574b4a4b566a37616158796e375679717465566f4771727764414b485538684747313974695951676558416f0000000000000000000000\",\"to\":{},\"from\":\"0x6c1e1bc39b13f9e0af9424d76de899203f47755f\",\"gasLimit\":{},\"speed\":\"fast\"}, code=UNPREDICTABLE_GAS_LIMIT, version=defender-relay-client)",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createProfile"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "reason": "cannot estimate gas; transaction may fail or may require manual gas limit",
                    "code": "UNPREDICTABLE_GAS_LIMIT",
                    "error": {
                        "reason": "cannot estimate gas; transaction may fail or may require manual gas limit",
                        "code": "UNPREDICTABLE_GAS_LIMIT",
                        "error": {
                            "code": 3,
                            "data": "0x902815b9"
                        },
                        "method": "estimateGas",
                        "transaction": {
                            "from": "0x6C1e1bC39b13f9E0Af9424D76De899203F47755F",
                            "to": "0xF6BF84E5df229029C9D36dC7ABaCDBE9c0bd7b4F",
                            "data": "0xffea138e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bba7556f668a78dba5e7989b0d7ca4db6315546e00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000968656c6c6f6c656e730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a68747470733a2f2f697066732e696e667572612e696f2f697066732f516d61386d586f656f727650716f6444617a6637787141526f464433393473316e6a6b7a653771315834434b38550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d574b4a4b566a37616158796e375679717465566f4771727764414b485538684747313974695951676558416f0000000000000000000000",
                            "accessList": null
                        }
                    },
                    "tx": {
                        "data": "0xffea138e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bba7556f668a78dba5e7989b0d7ca4db6315546e00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000968656c6c6f6c656e730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a68747470733a2f2f697066732e696e667572612e696f2f697066732f516d61386d586f656f727650716f6444617a6637787141526f464433393473316e6a6b7a653771315834434b38550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d574b4a4b566a37616158796e375679717465566f4771727764414b485538684747313974695951676558416f0000000000000000000000",
                        "to": {},
                        "from": "0x6c1e1bc39b13f9e0af9424d76de899203f47755f",
                        "gasLimit": {},
                        "speed": "fast"
                    },
                    "stacktrace": [
                        "Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={\"reason\":\"cannot estimate gas; transaction may fail or may require manual gas limit\",\"code\":\"UNPREDICTABLE_GAS_LIMIT\",\"error\":{\"code\":3,\"data\":\"0x902815b9\"},\"method\":\"estimateGas\",\"transaction\":{\"from\":\"0x6C1e1bC39b13f9E0Af9424D76De899203F47755F\",\"to\":\"0xF6BF84E5df229029C9D36dC7ABaCDBE9c0bd7b4F\",\"data\":\"0xffea138e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bba7556f668a78dba5e7989b0d7ca4db6315546e00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000968656c6c6f6c656e730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a68747470733a2f2f697066732e696e667572612e696f2f697066732f516d61386d586f656f727650716f6444617a6637787141526f464433393473316e6a6b7a653771315834434b38550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d574b4a4b566a37616158796e375679717465566f4771727764414b485538684747313974695951676558416f0000000000000000000000\",\"accessList\":null}}, tx={\"data\":\"0xffea138e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bba7556f668a78dba5e7989b0d7ca4db6315546e00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000968656c6c6f6c656e730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004a68747470733a2f2f697066732e696e667572612e696f2f697066732f516d61386d586f656f727650716f6444617a6637787141526f464433393473316e6a6b7a653771315834434b38550000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d574b4a4b566a37616158796e375679717465566f4771727764414b485538684747313974695951676558416f0000000000000000000000\",\"to\":{},\"from\":\"0x6c1e1bc39b13f9e0af9424d76de899203f47755f\",\"gasLimit\":{},\"speed\":\"fast\"}, code=UNPREDICTABLE_GAS_LIMIT, version=defender-relay-client)",
                        "    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:199:21)",
                        "    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:208:20)",
                        "    at /usr/src/app/node_modules/defender-relay-client/lib/ethers/signer.js:101:31",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async Promise.all (index 3)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```

**Comment by joshstevens19** [comment]
not an issue confirmed with @bigint
