### ISSUE TITLE
ApolloError to updateProfile in LensAPI in mumbai

### ISSUE THREAD

**Issue by rtang03** [aave/lens-api-examples#26]
when send mutation to  https://api-mumbai.lens.dev/

```text
mutation {
  updateProfile(
    request: {
      profileId: "0x21"
      twitterUrl: "http://twitter.com/11"
      name: "tester"
      bio: "fullstack dev"
      location: "the earth"
      coverPicture: "https://google.com"
    }
  ) {
    id
  }
}
```

Output 
```json
{
  "errors": [
    {
      "message": "Unexpected token u in JSON at position 0",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateProfile"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "SyntaxError: Unexpected token u in JSON at position 0",
            "    at JSON.parse (<anonymous>)",
            "    at /usr/src/app/build/database/data-interceptors.js:17:31",
            "    at Array.reduce (<anonymous>)",
            "    at formatDataIn (/usr/src/app/build/database/data-interceptors.js:13:25)",
            "    at executeFormatDataIn (/usr/src/app/build/database/db-execution.js:112:49)",
            "    at none (/usr/src/app/build/database/db-execution.js:35:39)",
            "    at updateProfileOfflineDataDb (/usr/src/app/build/database/profile/queries/update-profile-offline-data.query.js:16:36)",
            "    at updateProfileOfflineData (/usr/src/app/build/services/profile.service.js:175:79)",
            "    at SharedProfileResolver.updateProfile (/usr/src/app/build/graphql/resolvers/profile/shared-profile-resolver.js:159:62)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)",
            "    at async /usr/src/app/node_modules/type-graphql/dist/resolvers/helpers.js:83:26",
            "    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)",
            "    at async /usr/src/app/node_modules/type-graphql/dist/resolvers/helpers.js:83:26",
            "    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

Seems to be an JSON.parse() error in the Apollo backend.

**Comment by joshstevens19** [comment]
found issue and fixed its deploying now
