### ISSUE TITLE
Bug with update-profile endpoint when twitterUrl param is an empty string

### ISSUE THREAD

**Issue by Kipitup** [aave/lens-api-examples#42]
In order to reproduce the bug:

- Go to `src/profile/update-profile.ts` file
- set the twitter url with an empty string: `twitterUrl: ""`
- run `npm run profile:update-profile`

Your request will pass without any error but then every time you query your profile, you'll get an error + the data:
Here is mine:
```json
{
  "errors": [
    {
      "message": "Expected a value of type \"Url\" but received: \"\"",
      "locations": [
        {
          "line": 9,
          "column": 7
        }
      ],
      "path": [
        "profiles",
        "items",
        0,
        "twitterUrl"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Expected a value of type \"Url\" but received: \"\"",
            "    at completeLeafValue (/usr/src/app/node_modules/graphql/execution/execute.js:656:11)",
            "    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:578:12)",
            "    at /usr/src/app/node_modules/graphql/execution/execute.js:469:16",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async Promise.all (index 5)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)"
          ]
        }
      }
    }
  ],
  "data": {
    "profiles": {
      "items": [
        {
          "id": "0xed",
          "name": "kipit",
          "bio": "",
          "location": "",
          "website": "",
          "twitterUrl": null,
          "picture": null,
          "handle": "kipitistesting",
          "coverPicture": null,
          "ownedBy": "0xE5C9569a58B7164D653e1a4b7D48dCB64bd19653",
}

```

This happens only with the twitter url. If you put an empty string for the website or the coverPicture, nothing happens.

**Comment by joshstevens19** [comment]
fixed deploying now
