### ISSUE TITLE
Cannot search via hashtag, after hiding publication

### ISSUE THREAD

**Issue by rtang03** [aave/lens-api-examples#72]
Previously, in the testnet, I created 2 Posts, with hashtag #Ofweb3dev. And, was able to "search" them via query = "Ofweb3dev" 

```
query {
  search(
    request: { query: "Ofweb3dev", type: PUBLICATION }
  ) {
    ... on PublicationSearchResult {
      items {
        ... on Post {
          id
        }
      }
      pageInfo {
        totalCount
      }
    }
  }
}
```

Later on, I hide one of two Posts. And, run the same search query again, it returns below error 

```
{
  "errors": [
    {
      "message": "Cannot read properties of null (reading 'version')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "search"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read properties of null (reading 'version')",
            "    at buildMetadataOutput (/usr/src/app/build/services/metadata.service.js:302:22)",
            "    at buildPublicationBaseType (/usr/src/app/build/services/publication.service.js:210:68)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async buildPostOutput (/usr/src/app/build/services/publication.service.js:112:13)",
            "    at async Promise.all (index 0)",
            "    at async searchPublications (/usr/src/app/build/services/search.service.js:14:19)",
            "    at async SearchResolver.search (/usr/src/app/build/graphql/resolvers/search/index.js:36:45)",
            "    at async dispatchHandler (/usr/src/app/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)",
            "    at async /usr/src/app/node_modules/type-graphql/dist/resolvers/helpers.js:83:26"
          ]
        }
      }
    }
  ],
  "data": null
}
```

I guess a bug in search query for hidden publication.

**Comment by joshstevens19** [comment]
should not be an issue anymore
